### ISSUE TITLE
No way to deal with example chapter 2

### ISSUE THREAD

**Issue by laurentbellec** [PacktPublishing/Mastering-Angular-2-Components#1]
I cloned the code from the repository and that's what I got
![ch2](https://cloud.githubusercontent.com/assets/24356222/21646584/06f095ee-d297-11e6-868c-fd7b56520316.jpg)
Could you please have a look

**Comment by laurentbellec** [comment]
Same with chapter 3 :-(

**Comment by Mobasher-NetLinks** [comment]
I have another problem in chapter 2 before creating the task list:
I have the following files:
1- index.html
2- lib>app.html
3- lib>app.js
4- lib> bootstrap.js
`Unhandled Promise rejection: (SystemJS) platform_browser_dynamic_1.bootstrap is not a function
	TypeError: platform_browser_dynamic_1.bootstrap is not a function
	    at execute (http://127.0.0.1:8080/lib/bootstrap.js!transpiled:17:40)
	    at ZoneDelegate.invoke (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2-polyfills.js:390:29)
	    at Zone.run (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2-polyfills.js:283:44)
	Error loading http://127.0.0.1:8080/lib/bootstrap.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) platform_browser_dynamic_1.bootstrap is not a function
	TypeError: platform_browser_dynamic_1.bootstrap is not a function
	    at execute (http://127.0.0.1:8080/lib/bootstrap.js!transpiled:17:40)
	    at ZoneDelegate.invoke (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2-polyfills.js:390:29)
	    at Zone.run (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2-polyfills.js:283:44)
	Error loading http://127.0.0.1:8080/lib/bootstrap.js
	    at execute (http://127.0.0.1:8080/lib/bootstrap.js!transpiled:17:40)
	    at ZoneDelegate.invoke (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2-polyfills.js:390:29)
	    at Zone.run (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2-polyfills.js:283:44)
	Error loading http://127.0.0.1:8080/lib/bootstrap.js`

**Comment by sohamapackt** [comment]
Hi,

I am closing the issue. 
In case the issue still persists, feel free to reopen it.

Thanks

**Comment by laurentbellec** [comment]
Waouw, did you really reply ? ...after more than 3 years :-D to ask if the problem persist :-D
